<ul>
    <?php foreach ($datos as $row) : ?>
        <li>
            <label><?php echo $row["umeta_id"]; ?></label>            
            <button class="btn-primary"><?php echo $row["meta_key"]; ?></button>
        </li>            
    <?php endforeach; ?>
</ul>
<script type="text/javascript">
    $(function() {
        $(document).on("click", "button", function() {
            $(this).toggleClass("btn-danger");
        });
    });
</script>